//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helenium.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helenium.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Administrators can use this tools. Application will close now..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP error.
        /// </summary>
        public static string HTTPerror {
            get {
                return ResourceManager.GetString("HTTPerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        public static string Internalerror {
            get {
                return ResourceManager.GetString("Internalerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more URLS to visit.
        /// </summary>
        public static string NomoreURLStovisit {
            get {
                return ResourceManager.GetString("NomoreURLStovisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions needed.
        /// </summary>
        public static string Permissionsneeded {
            get {
                return ResourceManager.GetString("Permissionsneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Error.
        /// </summary>
        public static string ScriptError {
            get {
                return ResourceManager.GetString("ScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the test and close the application?.
        /// </summary>
        public static string Stopthetestandclosetheapplication {
            get {
                return ResourceManager.GetString("Stopthetestandclosetheapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test is continued.
        /// </summary>
        public static string Testiscontinued {
            get {
                return ResourceManager.GetString("Testiscontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test is paused.
        /// </summary>
        public static string Testispaused {
            get {
                return ResourceManager.GetString("Testispaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test is started, User: {0}, Computer: {1}.
        /// </summary>
        public static string Testisstarted {
            get {
                return ResourceManager.GetString("Testisstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test stopped.
        /// </summary>
        public static string Teststopped {
            get {
                return ResourceManager.GetString("Teststopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be visited.
        /// </summary>
        public static string Tobevisited {
            get {
                return ResourceManager.GetString("Tobevisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}, Visited: {1}, Todo: {2}.
        /// </summary>
        public static string TVT {
            get {
                return ResourceManager.GetString("TVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited.
        /// </summary>
        public static string Visited {
            get {
                return ResourceManager.GetString("Visited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
